#
# gromacs-chtc.sub
# My very first Condor submit description file
#
# Define a name for the job, which will also be  the executable's name
#
job = gromacs-chtc.sh
#
# Specify the Condor universe, executable and log file
#
notification = NEVER
universe = vanilla
executable = $(job)
log = $(job)_$(Cluster).log
output = $(job)_$(Cluster).out
error = $(job)_$(Cluster).err
#
# Specify that Condor should transfer files to and from
# the remote execution hosts for us. We do not have a shared
# file system connected to the execution hosts in the CHTC.
#
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
#
#transfer_input_files = /home/kfwong/Packages/gromacs/bin/grompp, /home/kfwong/Packages/gromacs/bin/mdrun, /home/kfwong/Packages/gromacs/bin/g_dist, /home/kfwong/Packages/gromacs/bin/g_traj, md-genvel.mdp, ch4.itp, initial.gro, methane.ndx, methane.top 
#
transfer_input_files = /home/kfwong/Packages/gromacs/bin/mdrun, /home/kfwong/Packages/gromacs/bin/g_dist, /home/kfwong/Packages/gromacs/bin/g_traj, seg.tpr, methane.ndx

queue
